<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class CreateTaskResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\CreateTask200ApplicationJSON $createTask200ApplicationJSONObject
     */
	
    public ?CreateTask200ApplicationJSON $createTask200ApplicationJSONObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\CreateTask401ApplicationJSON $createTask401ApplicationJSONObject
     */
	
    public ?CreateTask401ApplicationJSON $createTask401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\CreateTask403ApplicationJSON $createTask403ApplicationJSONObject
     */
	
    public ?CreateTask403ApplicationJSON $createTask403ApplicationJSONObject = null;
    
    /**
     * Invalid data posted
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\CreateTask422ApplicationJSON $createTask422ApplicationJSONObject
     */
	
    public ?CreateTask422ApplicationJSON $createTask422ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->createTask200ApplicationJSONObject = null;
		$this->createTask401ApplicationJSONObject = null;
		$this->createTask403ApplicationJSONObject = null;
		$this->createTask422ApplicationJSONObject = null;
	}
}
