<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class CreateOfficeResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Created
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\CreateOffice201ApplicationJSON $createOffice201ApplicationJSONObject
     */
	
    public ?CreateOffice201ApplicationJSON $createOffice201ApplicationJSONObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\CreateOffice401ApplicationJSON $createOffice401ApplicationJSONObject
     */
	
    public ?CreateOffice401ApplicationJSON $createOffice401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\CreateOffice403ApplicationJSON $createOffice403ApplicationJSONObject
     */
	
    public ?CreateOffice403ApplicationJSON $createOffice403ApplicationJSONObject = null;
    
    /**
     * Invalid data posted
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\CreateOffice422ApplicationJSON $createOffice422ApplicationJSONObject
     */
	
    public ?CreateOffice422ApplicationJSON $createOffice422ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->createOffice201ApplicationJSONObject = null;
		$this->createOffice401ApplicationJSONObject = null;
		$this->createOffice403ApplicationJSONObject = null;
		$this->createOffice422ApplicationJSONObject = null;
	}
}
