<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class CreateContractResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Created
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\CreateContract201ApplicationJSON $createContract201ApplicationJSONObject
     */
	
    public ?CreateContract201ApplicationJSON $createContract201ApplicationJSONObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\CreateContract401ApplicationJSON $createContract401ApplicationJSONObject
     */
	
    public ?CreateContract401ApplicationJSON $createContract401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\CreateContract403ApplicationJSON $createContract403ApplicationJSONObject
     */
	
    public ?CreateContract403ApplicationJSON $createContract403ApplicationJSONObject = null;
    
    /**
     * Invalid data posted
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\CreateContract422ApplicationJSON $createContract422ApplicationJSONObject
     */
	
    public ?CreateContract422ApplicationJSON $createContract422ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->createContract201ApplicationJSONObject = null;
		$this->createContract401ApplicationJSONObject = null;
		$this->createContract403ApplicationJSONObject = null;
		$this->createContract422ApplicationJSONObject = null;
	}
}
