<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class CurrentUserResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\CurrentUser200ApplicationJSON $currentUser200ApplicationJSONObject
     */
	
    public ?CurrentUser200ApplicationJSON $currentUser200ApplicationJSONObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\CurrentUser401ApplicationJSON $currentUser401ApplicationJSONObject
     */
	
    public ?CurrentUser401ApplicationJSON $currentUser401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\CurrentUser403ApplicationJSON $currentUser403ApplicationJSONObject
     */
	
    public ?CurrentUser403ApplicationJSON $currentUser403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->currentUser200ApplicationJSONObject = null;
		$this->currentUser401ApplicationJSONObject = null;
		$this->currentUser403ApplicationJSONObject = null;
	}
}
