<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class DeleteTaskResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteTask401ApplicationJSON $deleteTask401ApplicationJSONObject
     */
	
    public ?DeleteTask401ApplicationJSON $deleteTask401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteTask403ApplicationJSON $deleteTask403ApplicationJSONObject
     */
	
    public ?DeleteTask403ApplicationJSON $deleteTask403ApplicationJSONObject = null;
    
    /**
     * Not Found
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteTask404ApplicationJSON $deleteTask404ApplicationJSONObject
     */
	
    public ?DeleteTask404ApplicationJSON $deleteTask404ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->deleteTask401ApplicationJSONObject = null;
		$this->deleteTask403ApplicationJSONObject = null;
		$this->deleteTask404ApplicationJSONObject = null;
	}
}
