<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class DeleteRelationResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Precondition failed
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteRelation400ApplicationJSON $deleteRelation400ApplicationJSONObject
     */
	
    public ?DeleteRelation400ApplicationJSON $deleteRelation400ApplicationJSONObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteRelation401ApplicationJSON $deleteRelation401ApplicationJSONObject
     */
	
    public ?DeleteRelation401ApplicationJSON $deleteRelation401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteRelation403ApplicationJSON $deleteRelation403ApplicationJSONObject
     */
	
    public ?DeleteRelation403ApplicationJSON $deleteRelation403ApplicationJSONObject = null;
    
    /**
     * Not Found
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteRelation404ApplicationJSON $deleteRelation404ApplicationJSONObject
     */
	
    public ?DeleteRelation404ApplicationJSON $deleteRelation404ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->deleteRelation400ApplicationJSONObject = null;
		$this->deleteRelation401ApplicationJSONObject = null;
		$this->deleteRelation403ApplicationJSONObject = null;
		$this->deleteRelation404ApplicationJSONObject = null;
	}
}
