<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class DeleteOfficeResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Precondition failed
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteOffice400ApplicationJSON $deleteOffice400ApplicationJSONObject
     */
	
    public ?DeleteOffice400ApplicationJSON $deleteOffice400ApplicationJSONObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteOffice401ApplicationJSON $deleteOffice401ApplicationJSONObject
     */
	
    public ?DeleteOffice401ApplicationJSON $deleteOffice401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteOffice403ApplicationJSON $deleteOffice403ApplicationJSONObject
     */
	
    public ?DeleteOffice403ApplicationJSON $deleteOffice403ApplicationJSONObject = null;
    
    /**
     * Not Found
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteOffice404ApplicationJSON $deleteOffice404ApplicationJSONObject
     */
	
    public ?DeleteOffice404ApplicationJSON $deleteOffice404ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->deleteOffice400ApplicationJSONObject = null;
		$this->deleteOffice401ApplicationJSONObject = null;
		$this->deleteOffice403ApplicationJSONObject = null;
		$this->deleteOffice404ApplicationJSONObject = null;
	}
}
