<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class DeleteDocumentResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteDocument401ApplicationJSON $deleteDocument401ApplicationJSONObject
     */
	
    public ?DeleteDocument401ApplicationJSON $deleteDocument401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteDocument403ApplicationJSON $deleteDocument403ApplicationJSONObject
     */
	
    public ?DeleteDocument403ApplicationJSON $deleteDocument403ApplicationJSONObject = null;
    
    /**
     * Not Found
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteDocument404ApplicationJSON $deleteDocument404ApplicationJSONObject
     */
	
    public ?DeleteDocument404ApplicationJSON $deleteDocument404ApplicationJSONObject = null;
    
    /**
     * Invalid data posted
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteDocument422ApplicationJSON $deleteDocument422ApplicationJSONObject
     */
	
    public ?DeleteDocument422ApplicationJSON $deleteDocument422ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->deleteDocument401ApplicationJSONObject = null;
		$this->deleteDocument403ApplicationJSONObject = null;
		$this->deleteDocument404ApplicationJSONObject = null;
		$this->deleteDocument422ApplicationJSONObject = null;
	}
}
