<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class DeleteDepartmentResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Precondition failed
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteDepartment400ApplicationJSON $deleteDepartment400ApplicationJSONObject
     */
	
    public ?DeleteDepartment400ApplicationJSON $deleteDepartment400ApplicationJSONObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteDepartment401ApplicationJSON $deleteDepartment401ApplicationJSONObject
     */
	
    public ?DeleteDepartment401ApplicationJSON $deleteDepartment401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteDepartment403ApplicationJSON $deleteDepartment403ApplicationJSONObject
     */
	
    public ?DeleteDepartment403ApplicationJSON $deleteDepartment403ApplicationJSONObject = null;
    
    /**
     * Not Found
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteDepartment404ApplicationJSON $deleteDepartment404ApplicationJSONObject
     */
	
    public ?DeleteDepartment404ApplicationJSON $deleteDepartment404ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->deleteDepartment400ApplicationJSONObject = null;
		$this->deleteDepartment401ApplicationJSONObject = null;
		$this->deleteDepartment403ApplicationJSONObject = null;
		$this->deleteDepartment404ApplicationJSONObject = null;
	}
}
