<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class DeleteOfficeResponse
{
    /**
     * Precondition failed
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteOfficeResponseBody $fourHundredApplicationJsonObject
     */
	
    public ?DeleteOfficeResponseBody $fourHundredApplicationJsonObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteOfficeOfficesResponseBody $fourHundredAndOneApplicationJsonObject
     */
	
    public ?DeleteOfficeOfficesResponseBody $fourHundredAndOneApplicationJsonObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteOfficeOfficesResponseResponseBody $fourHundredAndThreeApplicationJsonObject
     */
	
    public ?DeleteOfficeOfficesResponseResponseBody $fourHundredAndThreeApplicationJsonObject = null;
    
    /**
     * Not Found
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\DeleteOfficeOfficesResponse404ResponseBody $fourHundredAndFourApplicationJsonObject
     */
	
    public ?DeleteOfficeOfficesResponse404ResponseBody $fourHundredAndFourApplicationJsonObject = null;
    
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse;
    
	public function __construct()
	{
		$this->fourHundredApplicationJsonObject = null;
		$this->fourHundredAndOneApplicationJsonObject = null;
		$this->fourHundredAndThreeApplicationJsonObject = null;
		$this->fourHundredAndFourApplicationJsonObject = null;
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
