<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class GetDocumentResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\GetDocument200ApplicationJSON $getDocument200ApplicationJSONObject
     */
	
    public ?GetDocument200ApplicationJSON $getDocument200ApplicationJSONObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\GetDocument401ApplicationJSON $getDocument401ApplicationJSONObject
     */
	
    public ?GetDocument401ApplicationJSON $getDocument401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\GetDocument403ApplicationJSON $getDocument403ApplicationJSONObject
     */
	
    public ?GetDocument403ApplicationJSON $getDocument403ApplicationJSONObject = null;
    
    /**
     * Not Found
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\GetDocument404ApplicationJSON $getDocument404ApplicationJSONObject
     */
	
    public ?GetDocument404ApplicationJSON $getDocument404ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getDocument200ApplicationJSONObject = null;
		$this->getDocument401ApplicationJSONObject = null;
		$this->getDocument403ApplicationJSONObject = null;
		$this->getDocument404ApplicationJSONObject = null;
	}
}
