<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;

use \Contractify\ContractifyAPI\Utils\SpeakeasyMetadata;
class GetDocumentRequest
{
    /**
     * Id of the company
     * 
     * @var int $company
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=company')]
    public int $company;
    
    /**
     * Id of the document
     * 
     * @var int $document
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=document')]
    public int $document;
    
	public function __construct()
	{
		$this->company = 0;
		$this->document = 0;
	}
}
