<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class GetOfficeResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\GetOffice200ApplicationJSON $getOffice200ApplicationJSONObject
     */
	
    public ?GetOffice200ApplicationJSON $getOffice200ApplicationJSONObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\GetOffice401ApplicationJSON $getOffice401ApplicationJSONObject
     */
	
    public ?GetOffice401ApplicationJSON $getOffice401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\GetOffice403ApplicationJSON $getOffice403ApplicationJSONObject
     */
	
    public ?GetOffice403ApplicationJSON $getOffice403ApplicationJSONObject = null;
    
    /**
     * Not Found
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\GetOffice404ApplicationJSON $getOffice404ApplicationJSONObject
     */
	
    public ?GetOffice404ApplicationJSON $getOffice404ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getOffice200ApplicationJSONObject = null;
		$this->getOffice401ApplicationJSONObject = null;
		$this->getOffice403ApplicationJSONObject = null;
		$this->getOffice404ApplicationJSONObject = null;
	}
}
