<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;

use \Contractify\ContractifyAPI\Utils\SpeakeasyMetadata;
class GetTaskRequest
{
    /**
     * Id of the company
     * 
     * @var int $company
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=company')]
    public int $company;
    
    /**
     * Id of the task
     * 
     * @var int $task
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=task')]
    public int $task;
    
	public function __construct()
	{
		$this->company = 0;
		$this->task = 0;
	}
}
