<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class GetTaskResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\GetTask200ApplicationJSON $getTask200ApplicationJSONObject
     */
	
    public ?GetTask200ApplicationJSON $getTask200ApplicationJSONObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\GetTask401ApplicationJSON $getTask401ApplicationJSONObject
     */
	
    public ?GetTask401ApplicationJSON $getTask401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\GetTask403ApplicationJSON $getTask403ApplicationJSONObject
     */
	
    public ?GetTask403ApplicationJSON $getTask403ApplicationJSONObject = null;
    
    /**
     * Not Found
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\GetTask404ApplicationJSON $getTask404ApplicationJSONObject
     */
	
    public ?GetTask404ApplicationJSON $getTask404ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getTask200ApplicationJSONObject = null;
		$this->getTask401ApplicationJSONObject = null;
		$this->getTask403ApplicationJSONObject = null;
		$this->getTask404ApplicationJSONObject = null;
	}
}
