<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;

use \Contractify\ContractifyAPI\Utils\SpeakeasyMetadata;
class ListDocumentsRequest
{
    /**
     * Id of the company
     * 
     * @var int $company
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=company')]
    public int $company;
    
    /**
     * Return documents currently having this status in the eSigning process, can be comma separated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListDocumentsEsigningStatus $esigningStatus
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=esigning_status')]
    public ?ListDocumentsEsigningStatus $esigningStatus = null;
    
    /**
     * Return documents where e-signing was updated after the given date
     * 
     * @var ?\DateTime $esigningUpdatedAfter
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=esigning_updated_after,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $esigningUpdatedAfter = null;
    
    /**
     * The page to retrieve
     * 
     * @var ?int $page
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?int $page = null;
    
    /**
     * Return documents linked to a relation
     * 
     * @var ?int $relationId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=relation_id')]
    public ?int $relationId = null;
    
    /**
     * Return documents e-signed after the given date
     * 
     * @var ?\DateTime $signedAfter
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=signed_after,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $signedAfter = null;
    
	public function __construct()
	{
		$this->company = 0;
		$this->esigningStatus = null;
		$this->esigningUpdatedAfter = null;
		$this->page = null;
		$this->relationId = null;
		$this->signedAfter = null;
	}
}
