<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class ListSubfoldersResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Shared\DossierCollection $dossierCollection
     */
	
    public ?\Contractify\ContractifyAPI\Models\Shared\DossierCollection $dossierCollection = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListSubfolders401ApplicationJSON $listSubfolders401ApplicationJSONObject
     */
	
    public ?ListSubfolders401ApplicationJSON $listSubfolders401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListSubfolders403ApplicationJSON $listSubfolders403ApplicationJSONObject
     */
	
    public ?ListSubfolders403ApplicationJSON $listSubfolders403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->dossierCollection = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listSubfolders401ApplicationJSONObject = null;
		$this->listSubfolders403ApplicationJSONObject = null;
	}
}
