<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class ListRelationsResponse
{
	
    public string $contentType;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Shared\RelationCollection $relationCollection
     */
	
    public ?\Contractify\ContractifyAPI\Models\Shared\RelationCollection $relationCollection = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListRelations401ApplicationJSON $listRelations401ApplicationJSONObject
     */
	
    public ?ListRelations401ApplicationJSON $listRelations401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListRelations403ApplicationJSON $listRelations403ApplicationJSONObject
     */
	
    public ?ListRelations403ApplicationJSON $listRelations403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->relationCollection = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listRelations401ApplicationJSONObject = null;
		$this->listRelations403ApplicationJSONObject = null;
	}
}
