<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class ListLegalEntitiesResponse
{
	
    public string $contentType;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Shared\LegalEntityCollection $legalEntityCollection
     */
	
    public ?\Contractify\ContractifyAPI\Models\Shared\LegalEntityCollection $legalEntityCollection = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListLegalEntities401ApplicationJSON $listLegalEntities401ApplicationJSONObject
     */
	
    public ?ListLegalEntities401ApplicationJSON $listLegalEntities401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListLegalEntities403ApplicationJSON $listLegalEntities403ApplicationJSONObject
     */
	
    public ?ListLegalEntities403ApplicationJSON $listLegalEntities403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->legalEntityCollection = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listLegalEntities401ApplicationJSONObject = null;
		$this->listLegalEntities403ApplicationJSONObject = null;
	}
}
