<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class ListContractsResponse
{
	
    public string $contentType;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Shared\ContractCollection $contractCollection
     */
	
    public ?\Contractify\ContractifyAPI\Models\Shared\ContractCollection $contractCollection = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListContracts401ApplicationJSON $listContracts401ApplicationJSONObject
     */
	
    public ?ListContracts401ApplicationJSON $listContracts401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListContracts403ApplicationJSON $listContracts403ApplicationJSONObject
     */
	
    public ?ListContracts403ApplicationJSON $listContracts403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->contractCollection = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listContracts401ApplicationJSONObject = null;
		$this->listContracts403ApplicationJSONObject = null;
	}
}
