<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class ListUsersResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Shared\UserCollection $userCollection
     */
	
    public ?\Contractify\ContractifyAPI\Models\Shared\UserCollection $userCollection = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListUsers401ApplicationJSON $listUsers401ApplicationJSONObject
     */
	
    public ?ListUsers401ApplicationJSON $listUsers401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListUsers403ApplicationJSON $listUsers403ApplicationJSONObject
     */
	
    public ?ListUsers403ApplicationJSON $listUsers403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->userCollection = null;
		$this->listUsers401ApplicationJSONObject = null;
		$this->listUsers403ApplicationJSONObject = null;
	}
}
