<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class ListOfficesResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Shared\OfficeCollection $officeCollection
     */
	
    public ?\Contractify\ContractifyAPI\Models\Shared\OfficeCollection $officeCollection = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListOffices401ApplicationJSON $listOffices401ApplicationJSONObject
     */
	
    public ?ListOffices401ApplicationJSON $listOffices401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListOffices403ApplicationJSON $listOffices403ApplicationJSONObject
     */
	
    public ?ListOffices403ApplicationJSON $listOffices403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->officeCollection = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listOffices401ApplicationJSONObject = null;
		$this->listOffices403ApplicationJSONObject = null;
	}
}
