<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class ListContractTypesResponse
{
	
    public string $contentType;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Shared\ContractTypeCollection $contractTypeCollection
     */
	
    public ?\Contractify\ContractifyAPI\Models\Shared\ContractTypeCollection $contractTypeCollection = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListContractTypes401ApplicationJSON $listContractTypes401ApplicationJSONObject
     */
	
    public ?ListContractTypes401ApplicationJSON $listContractTypes401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListContractTypes403ApplicationJSON $listContractTypes403ApplicationJSONObject
     */
	
    public ?ListContractTypes403ApplicationJSON $listContractTypes403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->contractTypeCollection = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listContractTypes401ApplicationJSONObject = null;
		$this->listContractTypes403ApplicationJSONObject = null;
	}
}
