<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;

use \Contractify\ContractifyAPI\Utils\SpeakeasyMetadata;
class ListUsersRequest
{
    /**
     * Id of the company
     * 
     * @var int $company
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=company')]
    public int $company;
    
    /**
     * The page to retrieve
     * 
     * @var ?int $page
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?int $page = null;
    
	public function __construct()
	{
		$this->company = 0;
		$this->page = null;
	}
}
