<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class ListTasksResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Shared\TaskCollection $taskCollection
     */
	
    public ?\Contractify\ContractifyAPI\Models\Shared\TaskCollection $taskCollection = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListTasks401ApplicationJSON $listTasks401ApplicationJSONObject
     */
	
    public ?ListTasks401ApplicationJSON $listTasks401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListTasks403ApplicationJSON $listTasks403ApplicationJSONObject
     */
	
    public ?ListTasks403ApplicationJSON $listTasks403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->taskCollection = null;
		$this->listTasks401ApplicationJSONObject = null;
		$this->listTasks403ApplicationJSONObject = null;
	}
}
