<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class ListDepartmentsResponse
{
	
    public string $contentType;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Shared\DepartmentCollection $departmentCollection
     */
	
    public ?\Contractify\ContractifyAPI\Models\Shared\DepartmentCollection $departmentCollection = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListDepartments401ApplicationJSON $listDepartments401ApplicationJSONObject
     */
	
    public ?ListDepartments401ApplicationJSON $listDepartments401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListDepartments403ApplicationJSON $listDepartments403ApplicationJSONObject
     */
	
    public ?ListDepartments403ApplicationJSON $listDepartments403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->departmentCollection = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listDepartments401ApplicationJSONObject = null;
		$this->listDepartments403ApplicationJSONObject = null;
	}
}
