<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class ListCustomFieldsResponse
{
	
    public string $contentType;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Shared\CustomFieldCollection $customFieldCollection
     */
	
    public ?\Contractify\ContractifyAPI\Models\Shared\CustomFieldCollection $customFieldCollection = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListCustomFields401ApplicationJSON $listCustomFields401ApplicationJSONObject
     */
	
    public ?ListCustomFields401ApplicationJSON $listCustomFields401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\ListCustomFields403ApplicationJSON $listCustomFields403ApplicationJSONObject
     */
	
    public ?ListCustomFields403ApplicationJSON $listCustomFields403ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->customFieldCollection = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listCustomFields401ApplicationJSONObject = null;
		$this->listCustomFields403ApplicationJSONObject = null;
	}
}
