<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class UpdateTaskResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateTask200ApplicationJSON $updateTask200ApplicationJSONObject
     */
	
    public ?UpdateTask200ApplicationJSON $updateTask200ApplicationJSONObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateTask401ApplicationJSON $updateTask401ApplicationJSONObject
     */
	
    public ?UpdateTask401ApplicationJSON $updateTask401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateTask403ApplicationJSON $updateTask403ApplicationJSONObject
     */
	
    public ?UpdateTask403ApplicationJSON $updateTask403ApplicationJSONObject = null;
    
    /**
     * Not Found
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateTask404ApplicationJSON $updateTask404ApplicationJSONObject
     */
	
    public ?UpdateTask404ApplicationJSON $updateTask404ApplicationJSONObject = null;
    
    /**
     * Invalid data posted
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateTask422ApplicationJSON $updateTask422ApplicationJSONObject
     */
	
    public ?UpdateTask422ApplicationJSON $updateTask422ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->updateTask200ApplicationJSONObject = null;
		$this->updateTask401ApplicationJSONObject = null;
		$this->updateTask403ApplicationJSONObject = null;
		$this->updateTask404ApplicationJSONObject = null;
		$this->updateTask422ApplicationJSONObject = null;
	}
}
