<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class UpdateTaskResponse
{
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateTaskResponseBody $twoHundredApplicationJsonObject
     */
	
    public ?UpdateTaskResponseBody $twoHundredApplicationJsonObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateTaskTasksResponseBody $fourHundredAndOneApplicationJsonObject
     */
	
    public ?UpdateTaskTasksResponseBody $fourHundredAndOneApplicationJsonObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateTaskTasksResponseResponseBody $fourHundredAndThreeApplicationJsonObject
     */
	
    public ?UpdateTaskTasksResponseResponseBody $fourHundredAndThreeApplicationJsonObject = null;
    
    /**
     * Not Found
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateTaskTasksResponse404ResponseBody $fourHundredAndFourApplicationJsonObject
     */
	
    public ?UpdateTaskTasksResponse404ResponseBody $fourHundredAndFourApplicationJsonObject = null;
    
    /**
     * Invalid data posted
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateTaskTasksResponse422ResponseBody $fourHundredAndTwentyTwoApplicationJsonObject
     */
	
    public ?UpdateTaskTasksResponse422ResponseBody $fourHundredAndTwentyTwoApplicationJsonObject = null;
    
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse;
    
	public function __construct()
	{
		$this->twoHundredApplicationJsonObject = null;
		$this->fourHundredAndOneApplicationJsonObject = null;
		$this->fourHundredAndThreeApplicationJsonObject = null;
		$this->fourHundredAndFourApplicationJsonObject = null;
		$this->fourHundredAndTwentyTwoApplicationJsonObject = null;
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
