<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class UpdateDepartmentResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateDepartment200ApplicationJSON $updateDepartment200ApplicationJSONObject
     */
	
    public ?UpdateDepartment200ApplicationJSON $updateDepartment200ApplicationJSONObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateDepartment401ApplicationJSON $updateDepartment401ApplicationJSONObject
     */
	
    public ?UpdateDepartment401ApplicationJSON $updateDepartment401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateDepartment403ApplicationJSON $updateDepartment403ApplicationJSONObject
     */
	
    public ?UpdateDepartment403ApplicationJSON $updateDepartment403ApplicationJSONObject = null;
    
    /**
     * Not Found
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateDepartment404ApplicationJSON $updateDepartment404ApplicationJSONObject
     */
	
    public ?UpdateDepartment404ApplicationJSON $updateDepartment404ApplicationJSONObject = null;
    
    /**
     * Invalid data posted
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateDepartment422ApplicationJSON $updateDepartment422ApplicationJSONObject
     */
	
    public ?UpdateDepartment422ApplicationJSON $updateDepartment422ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->updateDepartment200ApplicationJSONObject = null;
		$this->updateDepartment401ApplicationJSONObject = null;
		$this->updateDepartment403ApplicationJSONObject = null;
		$this->updateDepartment404ApplicationJSONObject = null;
		$this->updateDepartment422ApplicationJSONObject = null;
	}
}
