<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class UpdateDocumentResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateDocument200ApplicationJSON $updateDocument200ApplicationJSONObject
     */
	
    public ?UpdateDocument200ApplicationJSON $updateDocument200ApplicationJSONObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateDocument401ApplicationJSON $updateDocument401ApplicationJSONObject
     */
	
    public ?UpdateDocument401ApplicationJSON $updateDocument401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateDocument403ApplicationJSON $updateDocument403ApplicationJSONObject
     */
	
    public ?UpdateDocument403ApplicationJSON $updateDocument403ApplicationJSONObject = null;
    
    /**
     * Not Found
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateDocument404ApplicationJSON $updateDocument404ApplicationJSONObject
     */
	
    public ?UpdateDocument404ApplicationJSON $updateDocument404ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->updateDocument200ApplicationJSONObject = null;
		$this->updateDocument401ApplicationJSONObject = null;
		$this->updateDocument403ApplicationJSONObject = null;
		$this->updateDocument404ApplicationJSONObject = null;
	}
}
