<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;

use \Contractify\ContractifyAPI\Utils\SpeakeasyMetadata;
class UpdateContractRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?\Contractify\ContractifyAPI\Models\Shared\ContractWrite $contractWrite = null;
    
    /**
     * Id of the company
     * 
     * @var int $company
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=company')]
    public int $company;
    
    /**
     * Id of the contract
     * 
     * @var int $contract
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=contract')]
    public int $contract;
    
	public function __construct()
	{
		$this->contractWrite = null;
		$this->company = 0;
		$this->contract = 0;
	}
}
