<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class UpdateOfficeResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateOffice200ApplicationJSON $updateOffice200ApplicationJSONObject
     */
	
    public ?UpdateOffice200ApplicationJSON $updateOffice200ApplicationJSONObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateOffice401ApplicationJSON $updateOffice401ApplicationJSONObject
     */
	
    public ?UpdateOffice401ApplicationJSON $updateOffice401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateOffice403ApplicationJSON $updateOffice403ApplicationJSONObject
     */
	
    public ?UpdateOffice403ApplicationJSON $updateOffice403ApplicationJSONObject = null;
    
    /**
     * Not Found
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateOffice404ApplicationJSON $updateOffice404ApplicationJSONObject
     */
	
    public ?UpdateOffice404ApplicationJSON $updateOffice404ApplicationJSONObject = null;
    
    /**
     * Invalid data posted
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateOffice422ApplicationJSON $updateOffice422ApplicationJSONObject
     */
	
    public ?UpdateOffice422ApplicationJSON $updateOffice422ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->updateOffice200ApplicationJSONObject = null;
		$this->updateOffice401ApplicationJSONObject = null;
		$this->updateOffice403ApplicationJSONObject = null;
		$this->updateOffice404ApplicationJSONObject = null;
		$this->updateOffice422ApplicationJSONObject = null;
	}
}
