<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;

use \Contractify\ContractifyAPI\Utils\SpeakeasyMetadata;
class UpdateRelationRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?\Contractify\ContractifyAPI\Models\Shared\RelationWrite $relationWrite = null;
    
    /**
     * Id of the company
     * 
     * @var int $company
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=company')]
    public int $company;
    
    /**
     * Id of the relation
     * 
     * @var int $relation
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=relation')]
    public int $relation;
    
	public function __construct()
	{
		$this->relationWrite = null;
		$this->company = 0;
		$this->relation = 0;
	}
}
