<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Operations;


class UpdateRelationResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateRelation200ApplicationJSON $updateRelation200ApplicationJSONObject
     */
	
    public ?UpdateRelation200ApplicationJSON $updateRelation200ApplicationJSONObject = null;
    
    /**
     * Unauthenticated
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateRelation401ApplicationJSON $updateRelation401ApplicationJSONObject
     */
	
    public ?UpdateRelation401ApplicationJSON $updateRelation401ApplicationJSONObject = null;
    
    /**
     * Forbidden
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateRelation403ApplicationJSON $updateRelation403ApplicationJSONObject
     */
	
    public ?UpdateRelation403ApplicationJSON $updateRelation403ApplicationJSONObject = null;
    
    /**
     * Not Found
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateRelation404ApplicationJSON $updateRelation404ApplicationJSONObject
     */
	
    public ?UpdateRelation404ApplicationJSON $updateRelation404ApplicationJSONObject = null;
    
    /**
     * Invalid data posted
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Operations\UpdateRelation422ApplicationJSON $updateRelation422ApplicationJSONObject
     */
	
    public ?UpdateRelation422ApplicationJSON $updateRelation422ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->updateRelation200ApplicationJSONObject = null;
		$this->updateRelation401ApplicationJSONObject = null;
		$this->updateRelation403ApplicationJSONObject = null;
		$this->updateRelation404ApplicationJSONObject = null;
		$this->updateRelation422ApplicationJSONObject = null;
	}
}
