<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Shared;


class ContractTypeNameRead
{
	#[\JMS\Serializer\Annotation\SerializedName('en')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $en = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('fr')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $fr = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('nl')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $nl = null;
    
	public function __construct()
	{
		$this->en = null;
		$this->fr = null;
		$this->nl = null;
	}
}
