<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Shared;


class ContractRead
{
    /**
     * $contractTypes
     * 
     * @var ?array<\Contractify\ContractifyAPI\Models\Shared\ContractTypeRead> $contractTypes
     */
	#[\JMS\Serializer\Annotation\SerializedName('contract_types')]
    #[\JMS\Serializer\Annotation\Type('array<Contractify\ContractifyAPI\Models\Shared\ContractTypeRead>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $contractTypes = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $createdAt = null;
    
    /**
     * $customFieldValues
     * 
     * @var ?array<\Contractify\ContractifyAPI\Models\Shared\CustomFieldValueRead> $customFieldValues
     */
	#[\JMS\Serializer\Annotation\SerializedName('custom_field_values')]
    #[\JMS\Serializer\Annotation\Type('array<Contractify\ContractifyAPI\Models\Shared\CustomFieldValueRead>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $customFieldValues = null;
    
    /**
     * $departments
     * 
     * @var ?array<\Contractify\ContractifyAPI\Models\Shared\DepartmentRead> $departments
     */
	#[\JMS\Serializer\Annotation\SerializedName('departments')]
    #[\JMS\Serializer\Annotation\Type('array<Contractify\ContractifyAPI\Models\Shared\DepartmentRead>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $departments = null;
    
    /**
     * $documents
     * 
     * @var ?array<\Contractify\ContractifyAPI\Models\Shared\ContractDocumentRead> $documents
     */
	#[\JMS\Serializer\Annotation\SerializedName('documents')]
    #[\JMS\Serializer\Annotation\Type('array<Contractify\ContractifyAPI\Models\Shared\ContractDocumentRead>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $documents = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('dossier')]
    #[\JMS\Serializer\Annotation\Type('Contractify\ContractifyAPI\Models\Shared\DossierRead')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?DossierRead $dossier = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('duration')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $duration = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('end_date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d', '', '|Y-m-d'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $endDate = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $id = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('is_open_ended')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $isOpenEnded = null;
    
    /**
     * $legalEntities
     * 
     * @var ?array<\Contractify\ContractifyAPI\Models\Shared\LegalEntityRead> $legalEntities
     */
	#[\JMS\Serializer\Annotation\SerializedName('legal_entities')]
    #[\JMS\Serializer\Annotation\Type('array<Contractify\ContractifyAPI\Models\Shared\LegalEntityRead>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $legalEntities = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
    /**
     * $offices
     * 
     * @var ?array<\Contractify\ContractifyAPI\Models\Shared\OfficeRead> $offices
     */
	#[\JMS\Serializer\Annotation\SerializedName('offices')]
    #[\JMS\Serializer\Annotation\Type('array<Contractify\ContractifyAPI\Models\Shared\OfficeRead>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $offices = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('owner_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $ownerId = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('permalink')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $permalink = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('phase')]
    #[\JMS\Serializer\Annotation\Type('enum<Contractify\ContractifyAPI\Models\Shared\ContractPhase>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ContractPhase $phase = null;
    
    /**
     * $relations
     * 
     * @var ?array<\Contractify\ContractifyAPI\Models\Shared\RelationRead> $relations
     */
	#[\JMS\Serializer\Annotation\SerializedName('relations')]
    #[\JMS\Serializer\Annotation\Type('array<Contractify\ContractifyAPI\Models\Shared\RelationRead>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $relations = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('renewal')]
    #[\JMS\Serializer\Annotation\Type('Contractify\ContractifyAPI\Models\Shared\ContractRenewal')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ContractRenewal $renewal = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('start_date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d', '', '|Y-m-d'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $startDate = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('termination')]
    #[\JMS\Serializer\Annotation\Type('Contractify\ContractifyAPI\Models\Shared\ContractTermination')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ContractTermination $termination = null;
    
	public function __construct()
	{
		$this->contractTypes = null;
		$this->createdAt = null;
		$this->customFieldValues = null;
		$this->departments = null;
		$this->documents = null;
		$this->dossier = null;
		$this->duration = null;
		$this->endDate = null;
		$this->id = null;
		$this->isOpenEnded = null;
		$this->legalEntities = null;
		$this->name = null;
		$this->offices = null;
		$this->ownerId = null;
		$this->permalink = null;
		$this->phase = null;
		$this->relations = null;
		$this->renewal = null;
		$this->startDate = null;
		$this->termination = null;
	}
}
