<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Shared;


enum ContractPhase: string
{
    case Tender = 'tender';
    case Ongoing = 'ongoing';
    case InTermination = 'in_termination';
    case Ended = 'ended';
    case InReview = 'in_review';
}
