<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Shared;


class ContractRenewal
{
	#[\JMS\Serializer\Annotation\SerializedName('automatic_renewal')]
    #[\JMS\Serializer\Annotation\Type('Contractify\ContractifyAPI\Models\Shared\ContractAutomaticRenewal')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ContractAutomaticRenewal $automaticRenewal = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('is_automatically_renewed')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $isAutomaticallyRenewed = null;
    
	public function __construct()
	{
		$this->automaticRenewal = null;
		$this->isAutomaticallyRenewed = null;
	}
}
