<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Shared;


class ContractAutomaticRenewal
{
	#[\JMS\Serializer\Annotation\SerializedName('number_of_renewals')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $numberOfRenewals = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('renewal_period')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $renewalPeriod = null;
    
	public function __construct()
	{
		$this->numberOfRenewals = null;
		$this->renewalPeriod = null;
	}
}
