<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Shared;


class ContractWrite
{
    /**
     * $contractTypes
     * 
     * @var ?array<int> $contractTypes
     */
	#[\JMS\Serializer\Annotation\SerializedName('contract_types')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $contractTypes = null;
    
    /**
     * $customFieldValues
     * 
     * @var ?array<\Contractify\ContractifyAPI\Models\Shared\CustomFieldValueWrite> $customFieldValues
     */
	#[\JMS\Serializer\Annotation\SerializedName('custom_field_values')]
    #[\JMS\Serializer\Annotation\Type('array<Contractify\ContractifyAPI\Models\Shared\CustomFieldValueWrite>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $customFieldValues = null;
    
    /**
     * $departments
     * 
     * @var ?array<int> $departments
     */
	#[\JMS\Serializer\Annotation\SerializedName('departments')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $departments = null;
    
    /**
     * $documents
     * 
     * @var ?array<int> $documents
     */
	#[\JMS\Serializer\Annotation\SerializedName('documents')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $documents = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('dossier_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $dossierId;
    
	#[\JMS\Serializer\Annotation\SerializedName('duration')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $duration = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('end_date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d', '', '|Y-m-d'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $endDate = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('is_open_ended')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $isOpenEnded = null;
    
    /**
     * $legalEntities
     * 
     * @var ?array<int> $legalEntities
     */
	#[\JMS\Serializer\Annotation\SerializedName('legal_entities')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $legalEntities = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * $offices
     * 
     * @var ?array<int> $offices
     */
	#[\JMS\Serializer\Annotation\SerializedName('offices')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $offices = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('owner_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $ownerId = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('phase')]
    #[\JMS\Serializer\Annotation\Type('enum<Contractify\ContractifyAPI\Models\Shared\ContractPhase>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ContractPhase $phase = null;
    
    /**
     * $relations
     * 
     * @var ?array<int> $relations
     */
	#[\JMS\Serializer\Annotation\SerializedName('relations')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $relations = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('renewal')]
    #[\JMS\Serializer\Annotation\Type('Contractify\ContractifyAPI\Models\Shared\ContractRenewal')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ContractRenewal $renewal = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('start_date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d', '', '|Y-m-d'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $startDate = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('termination')]
    #[\JMS\Serializer\Annotation\Type('Contractify\ContractifyAPI\Models\Shared\ContractTermination')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ContractTermination $termination = null;
    
	public function __construct()
	{
		$this->contractTypes = null;
		$this->customFieldValues = null;
		$this->departments = null;
		$this->documents = null;
		$this->dossierId = 0;
		$this->duration = null;
		$this->endDate = null;
		$this->isOpenEnded = null;
		$this->legalEntities = null;
		$this->name = "";
		$this->offices = null;
		$this->ownerId = null;
		$this->phase = null;
		$this->relations = null;
		$this->renewal = null;
		$this->startDate = null;
		$this->termination = null;
	}
}
