<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Shared;


class ContractTermination
{
	#[\JMS\Serializer\Annotation\SerializedName('is_terminable_at_any_time')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $isTerminableAtAnyTime = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('termination_date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d', '', '|Y-m-d'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $terminationDate = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('termination_duration')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $terminationDuration = null;
    
	public function __construct()
	{
		$this->isTerminableAtAnyTime = null;
		$this->terminationDate = null;
		$this->terminationDuration = null;
	}
}
