<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Shared;


class DocumentWrite
{
    /**
     * $contracts
     * 
     * @var ?array<int> $contracts
     */
	#[\JMS\Serializer\Annotation\SerializedName('contracts')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $contracts = null;
    
    /**
     * $customFieldValues
     * 
     * @var ?array<\Contractify\ContractifyAPI\Models\Shared\CustomFieldValueWrite> $customFieldValues
     */
	#[\JMS\Serializer\Annotation\SerializedName('custom_field_values')]
    #[\JMS\Serializer\Annotation\Type('array<Contractify\ContractifyAPI\Models\Shared\CustomFieldValueWrite>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $customFieldValues = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $description = null;
    
    /**
     * $dossiers
     * 
     * @var ?array<int> $dossiers
     */
	#[\JMS\Serializer\Annotation\SerializedName('dossiers')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $dossiers = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('owner_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $ownerId = null;
    
	public function __construct()
	{
		$this->contracts = null;
		$this->customFieldValues = null;
		$this->description = null;
		$this->dossiers = null;
		$this->name = "";
		$this->ownerId = null;
	}
}
