<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Shared;


/**
 * DossierCollection - OK
 * 
 * @package Contractify\ContractifyAPI\Models\Shared
 * @access public
 */
class DossierCollection
{
    /**
     * $data
     * 
     * @var ?array<\Contractify\ContractifyAPI\Models\Shared\DossierRead> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<Contractify\ContractifyAPI\Models\Shared\DossierRead>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $data = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('meta')]
    #[\JMS\Serializer\Annotation\Type('Contractify\ContractifyAPI\Models\Shared\Pagination')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Pagination $meta = null;
    
	public function __construct()
	{
		$this->data = null;
		$this->meta = null;
	}
}
