<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Shared;


/** Will only be accepted if you pass a `contract_id` */
enum TaskUpdateDueDateDependsOn: string
{
    case TerminationDate = 'termination_date';
    case EndDate = 'end_date';
    case StartDate = 'start_date';
}
