<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Shared;


class TaskWrite
{
	#[\JMS\Serializer\Annotation\SerializedName('contract_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $contractId = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $description = null;
    
    /**
     * Will be overwritten if `due_date_depends_on` and `due_date_interval` are passed
     * 
     * @var ?\DateTime $dueDate
     */
	#[\JMS\Serializer\Annotation\SerializedName('due_date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d', '', '|Y-m-d'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $dueDate = null;
    
    /**
     * Will only be accepted if you pass a `contract_id`
     * 
     * @var ?\Contractify\ContractifyAPI\Models\Shared\TaskWriteDueDateDependsOn $dueDateDependsOn
     */
	#[\JMS\Serializer\Annotation\SerializedName('due_date_depends_on')]
    #[\JMS\Serializer\Annotation\Type('enum<Contractify\ContractifyAPI\Models\Shared\TaskWriteDueDateDependsOn>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TaskWriteDueDateDependsOn $dueDateDependsOn = null;
    
    /**
     * Will only be accepted if you pass a `contract_id`
     * 
     * @var ?string $dueDateInterval
     */
	#[\JMS\Serializer\Annotation\SerializedName('due_date_interval')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $dueDateInterval = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('owner_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $ownerId = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('reminder_duration')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $reminderDuration = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('repetition_interval')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $repetitionInterval = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<Contractify\ContractifyAPI\Models\Shared\TaskWriteStatus>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TaskWriteStatus $status = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $title = null;
    
	public function __construct()
	{
		$this->contractId = null;
		$this->description = null;
		$this->dueDate = null;
		$this->dueDateDependsOn = null;
		$this->dueDateInterval = null;
		$this->ownerId = null;
		$this->reminderDuration = null;
		$this->repetitionInterval = null;
		$this->status = null;
		$this->title = null;
	}
}
