<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Shared;


class TaskCollection
{
    /**
     * $data
     * 
     * @var ?array<\Contractify\ContractifyAPI\Models\Shared\TaskRead> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<Contractify\ContractifyAPI\Models\Shared\TaskRead>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $data = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('meta')]
    #[\JMS\Serializer\Annotation\Type('Contractify\ContractifyAPI\Models\Shared\Pagination')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Pagination $meta = null;
    
	public function __construct()
	{
		$this->data = null;
		$this->meta = null;
	}
}
