<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Contractify\ContractifyAPI\Models\Shared;


enum UserReadRole: string
{
    case Admin = 'admin';
    case Manager = 'manager';
    case User = 'user';
}
